'use strict';

const PLANS = Object.freeze([
  {
    id: 'free',
    name: '免费版',
    tagline: '建立求职节奏',
    priceMonthly: 0,
    currency: 'CNY',
    availableForCheckout: false,
    availabilityLabel: '永久免费',
    features: ['基础岗位搜索与收藏', '求职进度管理', '每日基础练习', '多专业求职画像'],
    entitlements: {
      'profile.majors': 3,
      'prep.tracks': 2,
      'prep.attempts.daily': 5,
      'salary.insights': 0,
      'coach.feedback': 0,
    },
  },
  {
    id: 'pro',
    name: '专业版',
    tagline: '系统化拿到更合适的机会',
    priceMonthly: 3900,
    currency: 'CNY',
    availableForCheckout: true,
    availabilityLabel: '支付渠道接通后开放',
    features: ['更多专业方向', '全部备考路径', '薪酬区间洞察', '更高每日练习配额'],
    entitlements: {
      'profile.majors': 10,
      'prep.tracks': -1,
      'prep.attempts.daily': 100,
      'salary.insights': 1,
      'coach.feedback': 0,
    },
  },
  {
    id: 'coach',
    name: '求职加速版',
    tagline: '高强度冲刺服务预览',
    priceMonthly: 12900,
    currency: 'CNY',
    availableForCheckout: false,
    availabilityLabel: '真人服务筹备中',
    features: ['包含专业版全部权益', '更高练习配额', '真人辅导服务筹备中（暂不可购买）'],
    entitlements: {
      'profile.majors': 20,
      'prep.tracks': -1,
      'prep.attempts.daily': 500,
      'salary.insights': 1,
      'coach.feedback': 0,
    },
  },
]);

const PREP_TRACKS = Object.freeze([
  {
    id: 'track_job_search', order: 1, title: '求职基础与简历', icon: 'compass',
    description: '从岗位判断、经历表达和投递节奏开始，建立可持续的求职系统。',
    majors: ['不限专业'], roles: ['通用', '应届生', '转行'], difficulty: '基础',
  },
  {
    id: 'track_behavioral', order: 2, title: '行为面试与 STAR', icon: 'message-circle',
    description: '把真实经历讲得具体、有证据，并能应对追问。',
    majors: ['不限专业'], roles: ['通用', '管理培训生'], difficulty: '基础',
  },
  {
    id: 'track_software', order: 3, title: '软件与互联网研发', icon: 'code',
    description: '覆盖工程基础、系统思考和线上问题分析。',
    majors: ['计算机科学', '软件工程', '电子信息'], roles: ['软件工程师', '前端工程师', '后端工程师'], difficulty: '进阶',
  },
  {
    id: 'track_data', order: 4, title: '数据与商业分析', icon: 'chart',
    description: '从指标定义到实验判断，训练可解释的数据决策能力。',
    majors: ['统计学', '数学', '经济学', '计算机科学'], roles: ['数据分析师', '商业分析师'], difficulty: '进阶',
  },
  {
    id: 'track_product_ops', order: 5, title: '产品与运营', icon: 'layers',
    description: '围绕用户问题、优先级、增长和复盘组织答案。',
    majors: ['不限专业', '工商管理', '信息管理'], roles: ['产品经理', '用户运营', '增长运营'], difficulty: '进阶',
  },
  {
    id: 'track_marketing', order: 6, title: '市场、品牌与传媒', icon: 'megaphone',
    description: '训练受众洞察、传播策略、内容判断和效果复盘。',
    majors: ['市场营销', '新闻传播', '广告学', '中文'], roles: ['品牌营销', '市场专员', '内容运营'], difficulty: '进阶',
  },
  {
    id: 'track_finance', order: 7, title: '财务、金融与咨询', icon: 'briefcase',
    description: '建立财务逻辑、估值直觉与结构化商业判断。',
    majors: ['会计学', '金融学', '经济学', '工商管理'], roles: ['财务分析', '审计', '投行分析师', '咨询顾问'], difficulty: '进阶',
  },
  {
    id: 'track_engineering', order: 8, title: '工程制造与供应链', icon: 'settings',
    description: '覆盖质量、交付、工程取舍和供应链协同。',
    majors: ['机械工程', '电气工程', '自动化', '工业工程', '物流管理'], roles: ['机械工程师', '电气工程师', '质量工程师', '供应链专员'], difficulty: '进阶',
  },
]);

const PREP_QUESTIONS = Object.freeze([
  {
    id: 'q_job_1', trackId: 'track_job_search', type: 'single', difficulty: '基础',
    prompt: '阅读一条岗位描述时，最适合优先确认哪一项？',
    options: ['公司宣传口号', '岗位核心产出与硬性门槛', '招聘海报颜色', '职位名称是否流行'],
    answer: '岗位核心产出与硬性门槛',
    explanation: '先确认核心产出和硬门槛，才能判断岗位是否值得投入时间。',
  },
  {
    id: 'q_job_2', trackId: 'track_job_search', type: 'multi', difficulty: '基础',
    prompt: '一条更有说服力的简历经历通常包含哪些元素？',
    options: ['具体行动', '可核验结果', '任务背景', '空泛形容词'],
    answer: ['具体行动', '可核验结果', '任务背景'],
    explanation: '背景、行动和结果让招聘者能判断你的真实贡献。',
  },
  {
    id: 'q_job_3', trackId: 'track_job_search', type: 'short', difficulty: '基础',
    prompt: '你会怎样决定一周内各岗位的投递优先级？',
    answer: { keywords: ['匹配', '截止', '意愿', '准备成本'], sample: '综合匹配度、截止时间、个人意愿和准备成本排序，并为高优先岗位预留定制时间。' },
    explanation: '好的投递计划同时考虑机会价值和时间约束。',
  },
  {
    id: 'q_behavior_1', trackId: 'track_behavioral', type: 'single', difficulty: '基础',
    prompt: 'STAR 表达中的 R 代表什么？',
    options: ['角色', '资源', '结果', '复盘会议'],
    answer: '结果',
    explanation: 'R 是 Result，需要说明结果及其证据。',
  },
  {
    id: 'q_behavior_2', trackId: 'track_behavioral', type: 'multi', difficulty: '基础',
    prompt: '回答“讲一次失败经历”时，哪些做法更合适？',
    options: ['说明自己的责任', '给出具体改进', '把责任全部推给同事', '解释后来如何验证改进'],
    answer: ['说明自己的责任', '给出具体改进', '解释后来如何验证改进'],
    explanation: '面试官关注责任感、学习过程和改进是否真实发生。',
  },
  {
    id: 'q_behavior_3', trackId: 'track_behavioral', type: 'short', difficulty: '进阶',
    prompt: '面对“你如何处理意见冲突”，一个完整回答应覆盖什么？',
    answer: { keywords: ['目标', '事实', '沟通', '结果'], sample: '先对齐共同目标，再用事实澄清分歧，通过沟通形成方案，并说明执行结果。' },
    explanation: '冲突题需要证明你既能坚持判断，也能推动共同结果。',
  },
  {
    id: 'q_software_1', trackId: 'track_software', type: 'single', difficulty: '基础',
    prompt: '线上接口突然变慢，第一步最合理的做法是？',
    options: ['立即重写全部代码', '先确认指标、时间范围和影响面', '删除日志', '直接扩大所有服务器'],
    answer: '先确认指标、时间范围和影响面',
    explanation: '先界定症状和范围，才能避免无证据的修复。',
  },
  {
    id: 'q_software_2', trackId: 'track_software', type: 'multi', difficulty: '进阶',
    prompt: '设计幂等写接口时，可以使用哪些手段？',
    options: ['幂等键', '唯一约束', '请求结果缓存', '随机重复提交'],
    answer: ['幂等键', '唯一约束', '请求结果缓存'],
    explanation: '幂等键、唯一约束和结果复用共同降低重复执行风险。',
  },
  {
    id: 'q_software_3', trackId: 'track_software', type: 'short', difficulty: '进阶',
    prompt: '如何验证一次性能优化确实有效？',
    answer: { keywords: ['基线', '指标', '对照', '负载'], sample: '先记录同一负载下的基线，固定环境做对照实验，并比较延迟、吞吐和资源指标。' },
    explanation: '可复现的基线和受控对照比一次性的主观感受更可靠。',
  },
  {
    id: 'q_data_1', trackId: 'track_data', type: 'single', difficulty: '基础',
    prompt: '某产品注册人数上涨，但活跃率下降。首先应检查什么？',
    options: ['只汇报注册增长', '指标口径与用户分群变化', '更换图表颜色', '删除低活跃用户'],
    answer: '指标口径与用户分群变化',
    explanation: '总量和比率可能受渠道、口径及人群结构变化影响。',
  },
  {
    id: 'q_data_2', trackId: 'track_data', type: 'multi', difficulty: '进阶',
    prompt: '判断 A/B 实验结论是否可信时，应关注哪些因素？',
    options: ['样本量', '随机分流', '实验周期', '只看单日峰值'],
    answer: ['样本量', '随机分流', '实验周期'],
    explanation: '样本、分流和周期共同影响实验的统计与业务可信度。',
  },
  {
    id: 'q_data_3', trackId: 'track_data', type: 'short', difficulty: '进阶',
    prompt: '请简述如何为“求职推荐质量”定义指标。',
    answer: { keywords: ['点击', '收藏', '投递', '录用'], sample: '按漏斗定义推荐点击、收藏、投递和后续录用指标，并结合岗位覆盖率与用户满意度。' },
    explanation: '推荐质量应结合短期行为和长期求职结果。',
  },
  {
    id: 'q_product_1', trackId: 'track_product_ops', type: 'single', difficulty: '基础',
    prompt: '需求很多但研发资源有限时，产品经理最应先做什么？',
    options: ['全部承诺', '明确目标并比较用户价值、成本和风险', '只做声音最大的需求', '暂停沟通'],
    answer: '明确目标并比较用户价值、成本和风险',
    explanation: '优先级应服务于明确目标，并显式考虑价值、成本和风险。',
  },
  {
    id: 'q_product_2', trackId: 'track_product_ops', type: 'multi', difficulty: '进阶',
    prompt: '一次有效的功能复盘通常应包含哪些内容？',
    options: ['原始目标', '结果指标', '偏差原因', '下一步实验'],
    answer: ['原始目标', '结果指标', '偏差原因', '下一步实验'],
    explanation: '复盘需要从目标回到证据，并形成下一步行动。',
  },
  {
    id: 'q_product_3', trackId: 'track_product_ops', type: 'short', difficulty: '进阶',
    prompt: '如果新用户完成注册但不完善求职画像，你会怎样分析？',
    answer: { keywords: ['漏斗', '阻力', '价值', '实验'], sample: '拆解注册到画像完成的漏斗，访谈识别阻力与价值感知，再设计降低步骤或强化收益的实验。' },
    explanation: '先找到流失位置和原因，再验证解决方案。',
  },
  {
    id: 'q_marketing_1', trackId: 'track_marketing', type: 'single', difficulty: '基础',
    prompt: '制定传播方案前，最先需要明确什么？',
    options: ['受众和传播目标', '海报尺寸', '发布数量越多越好', '竞争对手字体'],
    answer: '受众和传播目标',
    explanation: '受众和目标决定信息、渠道与衡量方式。',
  },
  {
    id: 'q_marketing_2', trackId: 'track_marketing', type: 'multi', difficulty: '进阶',
    prompt: '评估内容营销效果时，可以组合哪些指标？',
    options: ['触达', '互动', '转化', '品牌搜索变化'],
    answer: ['触达', '互动', '转化', '品牌搜索变化'],
    explanation: '组合指标能同时观察传播规模、内容反应和业务结果。',
  },
  {
    id: 'q_marketing_3', trackId: 'track_marketing', type: 'short', difficulty: '进阶',
    prompt: '品牌出现负面讨论时，你会如何制定第一轮响应？',
    answer: { keywords: ['事实', '影响', '受众', '监测'], sample: '先核实事实和影响范围，识别核心受众，给出一致回应，并持续监测讨论与业务影响。' },
    explanation: '快速但基于事实的分级响应，比情绪化发声更可靠。',
  },
  {
    id: 'q_finance_1', trackId: 'track_finance', type: 'single', difficulty: '基础',
    prompt: '利润增长但经营现金流下降，最值得优先关注什么？',
    options: ['应收账款和存货变化', '公司标志', '员工座位', '报告页数'],
    answer: '应收账款和存货变化',
    explanation: '营运资本变化可能造成利润与现金流背离。',
  },
  {
    id: 'q_finance_2', trackId: 'track_finance', type: 'multi', difficulty: '进阶',
    prompt: '比较两家公司估值倍数时，需要考虑哪些差异？',
    options: ['增长率', '利润质量', '资本结构', '业务风险'],
    answer: ['增长率', '利润质量', '资本结构', '业务风险'],
    explanation: '倍数不能脱离增长、质量、结构和风险单独比较。',
  },
  {
    id: 'q_finance_3', trackId: 'track_finance', type: 'short', difficulty: '进阶',
    prompt: '咨询案例中，如何开始估算一个城市的咖啡市场规模？',
    answer: { keywords: ['人口', '渗透率', '频次', '客单价'], sample: '可从人口、饮用人群渗透率、购买频次和客单价逐层估算，并做上下限校验。' },
    explanation: '结构清晰、假设透明且可校验，比追求唯一数字更重要。',
  },
  {
    id: 'q_engineering_1', trackId: 'track_engineering', type: 'single', difficulty: '基础',
    prompt: '产线良率突然下降，第一步更合理的是？',
    options: ['先隔离异常批次并确认变化点', '立刻更换全部设备', '停止记录数据', '只要求加班'],
    answer: '先隔离异常批次并确认变化点',
    explanation: '先控制影响并找到时间、物料、设备或工艺变化点。',
  },
  {
    id: 'q_engineering_2', trackId: 'track_engineering', type: 'multi', difficulty: '进阶',
    prompt: '供应商交付风险评估应包含哪些方面？',
    options: ['交期稳定性', '质量表现', '产能弹性', '单一来源依赖'],
    answer: ['交期稳定性', '质量表现', '产能弹性', '单一来源依赖'],
    explanation: '交付、质量、容量和集中度共同决定供应风险。',
  },
  {
    id: 'q_engineering_3', trackId: 'track_engineering', type: 'short', difficulty: '进阶',
    prompt: '工程方案成本更低但可靠性略差，你会如何做取舍？',
    answer: { keywords: ['场景', '风险', '寿命', '验证'], sample: '结合使用场景、失效后果、全寿命成本和验证数据评估，必要时通过试验降低不确定性。' },
    explanation: '工程取舍应基于场景、全生命周期和可验证风险。',
  },
]);

const EXAM_PACKS = Object.freeze([
  {
    id: 'exam_huzhou_cloud', order: 1, title: '湖州城投集团 · 云端迁移样卷',
    subtitle: '把现有专项题库接入账号与云端进度的第一阶段样卷',
    description: '覆盖岗位判断、结构化表达和综合素质基础题。完整旧版专项题库仍可从原入口打开。',
    company: '湖州城投集团', roles: ['国企综合岗', '管理培训生', '职能岗'],
    majors: ['不限专业', '公共管理', '经济学', '法学'], year: 2026, type: '专项', difficulty: '基础',
    durationMinutes: 18, questionIds: ['q_job_1', 'q_job_2', 'q_job_3', 'q_behavior_1', 'q_behavior_2', 'q_behavior_3'],
    sourceLabel: '现有湖州城投题库迁移样卷', legacyUrl: '/exam/', featured: true,
  },
  {
    id: 'exam_job_foundations', order: 2, title: '通用求职与面试基础卷',
    subtitle: '适合所有专业的投递与表达热身',
    description: '从岗位判断、简历证据到 STAR 表达，快速检查求职基本功。',
    company: '通用', roles: ['应届生', '转行', '管理培训生'], majors: ['不限专业'],
    year: 2026, type: '模拟', difficulty: '基础', durationMinutes: 15,
    questionIds: ['q_job_1', 'q_job_2', 'q_job_3', 'q_behavior_1', 'q_behavior_2', 'q_behavior_3'],
    sourceLabel: '职路原创题库', legacyUrl: '', featured: true,
  },
  {
    id: 'exam_software_campus', order: 3, title: '软件工程校招基础卷',
    subtitle: '工程判断、接口设计与性能验证',
    description: '面向软件、计算机和电子信息专业，训练线上问题定位和可验证的工程思考。',
    company: '互联网与科技企业', roles: ['软件工程师', '前端工程师', '后端工程师'],
    majors: ['计算机科学', '软件工程', '电子信息'], year: 2026, type: '模拟', difficulty: '进阶',
    durationMinutes: 20, questionIds: ['q_job_1', 'q_job_2', 'q_job_3', 'q_software_1', 'q_software_2', 'q_software_3'],
    sourceLabel: '职路原创题库', legacyUrl: '', featured: false,
  },
  {
    id: 'exam_data_business', order: 4, title: '数据与商业分析综合卷',
    subtitle: '指标、实验、现金流与结构化估算',
    description: '适合数据、商业分析、金融和咨询方向，兼顾定量判断与业务表达。',
    company: '咨询、金融与科技企业', roles: ['数据分析师', '商业分析师', '咨询顾问', '财务分析'],
    majors: ['统计学', '数学', '经济学', '金融学'], year: 2026, type: '模拟', difficulty: '进阶',
    durationMinutes: 22, questionIds: ['q_data_1', 'q_data_2', 'q_data_3', 'q_finance_1', 'q_finance_2', 'q_finance_3'],
    sourceLabel: '职路原创题库', legacyUrl: '', featured: false,
  },
  {
    id: 'exam_product_marketing', order: 5, title: '产品、运营与品牌表达卷',
    subtitle: '用户问题、优先级、传播与复盘',
    description: '面向产品、运营、市场和传媒专业，训练从目标到结果的完整表达。',
    company: '消费、互联网与传媒企业', roles: ['产品经理', '用户运营', '品牌营销', '内容运营'],
    majors: ['工商管理', '市场营销', '新闻传播', '广告学'], year: 2026, type: '模拟', difficulty: '进阶',
    durationMinutes: 22, questionIds: ['q_product_1', 'q_product_2', 'q_product_3', 'q_marketing_1', 'q_marketing_2', 'q_marketing_3'],
    sourceLabel: '职路原创题库', legacyUrl: '', featured: false,
  },
  {
    id: 'exam_engineering_supply', order: 6, title: '工程制造与供应链卷',
    subtitle: '质量、交付、风险与工程取舍',
    description: '面向机械、电气、自动化、工业工程和供应链方向，覆盖真实工程决策场景。',
    company: '制造与工程企业', roles: ['机械工程师', '质量工程师', '供应链专员'],
    majors: ['机械工程', '电气工程', '自动化', '工业工程', '物流管理'], year: 2026, type: '模拟', difficulty: '进阶',
    durationMinutes: 20, questionIds: ['q_job_1', 'q_job_2', 'q_job_3', 'q_engineering_1', 'q_engineering_2', 'q_engineering_3'],
    sourceLabel: '职路原创题库', legacyUrl: '', featured: false,
  },
]);

module.exports = {
  EXAM_PACKS,
  PLANS,
  PREP_QUESTIONS,
  PREP_TRACKS,
};
